package com.trung.kotlinexample.model.loginResult

import com.google.gson.annotations.SerializedName

data class Organization(val endMns: Int = 0,
                        val mobileAllowSearchClient: Boolean = false,
                        val legacySmsTemplate: Boolean = false,
                        val gstEnabled: Boolean = false,
                        val maxEntityLimit: Int = 0,
                        val mobileShowDiscount: Boolean = false,
                        val qboSalesItemId: String? = null,
                        val enableRegions: Boolean = false,
                        val connectedToQbo: Boolean = false,
                        val enableCustomForms: Boolean = false,
                        val gstLabel: String = "",
                        val createdTime: String = "",
                        val sendPush: Boolean = false,
                        val autoSendSms: AutoSendSms?,
                        val mobileOrgHistoryPastDaysLimit: Int = 0,
                        val id: String = "",
                        val isResourcesEnabled: Boolean = false,
                        val isNotifyAdminEnabled: Boolean = false,
                        val gstTaxReferenceCode: String? = null,
                        val mobJobListLimitUpcoming: String = "",
                        val image: String? = null,
                        val enableQBO: Boolean = false,
                        val organizationName: String = "",
                        val unassignedContractJobReminderSettings: UnassignedContractJobReminderSettings?,
                        val gstValue: String = "",
                        val active: Boolean = false,
                        val mobileOrgHistoryOldEnabled: Boolean = false,
                        val hidePrice: Boolean = false,
                        val enableDataImportPage: Boolean = false,
                        val accessToken: String? = null,
                        val organizationEntities: List<OrganizationEntitiesItem>?,
                        val feedbackSettings: FeedbackSettings?,
                        val mobImageResolution: String = "",
                        val system: Boolean = false,
                        val mobileUpcomingFutureDaysLimit: Int = 0,
                        val pdfReportModel: String? = null,
                        val mobileShowClientServiceHistory: Boolean = false,
                        val newCalendar: Boolean = false,
                        val mobileOrgHistoryEnabled: Boolean = false,
                        val requestToken: String? = null,
                        val priceIncludeGst: Boolean = false,
                        val showUserServiceHistory: Boolean = false,
                        val organizationLevel: Int = 0,
                        val startingHrs: Int = 0,
                        val enableMandarine: Boolean = false,
                        val status: String? = null,
                        val mobileCaptureSignerImage: Boolean = false,
                        val gstRegistrationNumber: String? = null,
                        val mapView: MapView?,
                        val regions: String? = null,
                        val showAllServiceHistory: Boolean = false,
                        val mobImageQuality: String = "",
                        val description: String = "",
                        val locationHistoryVisibility: String = "",
                        val jobStartTime: String? = null,
                        val lastUpdatedUserId: String? = null,
                        val publicPagePath: String? = null,
                        val mobileCompletedEnabled: Boolean = false,
                        val jobReminderSettings: JobReminderSettings?,
                        val mobImageResolutionY: Int = 0,
                        val timeZoneCode: String = "",
                        val countryCode: String = "",
                        val breadCrumb: String? = null,
                        val mobImageResolutionX: Int = 0,
                        val endHrs: Int = 0,
                        val requestTokenSecret: String? = null,
                        val mobileAllowEdit: Boolean = false,
                        val lastUpdatedTime: String = "",
                        val mobileCompletedPastDaysLimit: Int = 0,
                        val mobileUpcomingPastDaysLimit: Int = 0,
                        val adminEmailRecipientType: String = "",
                        val defaultRegionId: String? = null,
                        val autoSendEmail: AutoSendEmail?,
                        val address: Address?,
                        val mobJobListLimitPast: String = "",
                        val lastModifiedBy: String = "",
                        val startingMns: Int = 0,
                        val cashCollectionSettings: CashCollectionSettings?,
                        val mobileRefreshPeriod: String = "",
                        val allowPastJobs: Boolean = false,
                        val parentId: String? = null,
                        val accessTokenSecret: String? = null,
                        @SerializedName("_refs")
                        val Refs: Refs?,
                        val enableCustomSMSSender: Boolean = false,
                        val clientVerificationType: String = "",
                        val mobileDisplayPrice: Boolean = false,
                        val defaultEntityId: String = "",
                        val createdBy: String = "",
                        val currencyCode: String = "",
                        val enablePublicPage: Boolean = false,
                        val qboid: String? = null)